### ISSUE TITLE
Squid Mat is entire block.

### ISSUE THREAD

**Issue by PieCoder314** [TEAMModding/KalStuff#1]
When I was testing the languages I made, I found out that the squid mat is an entire block, but the texture only takes up the lower portion. I don't know how to do this, but possibly turning it into a slab would fix it.

**Comment by CircuitLord** [comment]
Yeah, I saw that too. I don't know how to change it though.

**Comment by Kalman98** [comment]
Thank you, I will fix this immediately.

**Comment by Kalman98** [comment]
It has been fixed. The block can now be passed through, and the bounding box is a little taller than the mat model.
