### ISSUE TITLE
Won't load in 1.10

### ISSUE THREAD

**Issue by pianoman373** [TEAMModding/KalStuff#14]
Trying to load the mod in 1.10 gives:

Kalstuff (kalstuff) wants Minecraft [1.9, 1.9.1, 1.9.2 1.9.3, 1.9.4, 1.10, 1.10.1, 1.10.2]

It seems to be recognizing it as one big version.

**Comment by Kalman98** [comment]
Yes, I've been working on this actually. I think I may have found the answer though. It seems that 1.10 counts as 1.11 in the code for whatever reason, so I am testing it and will push it it works.

**Comment by pianoman373** [comment]
Yeah I looked at chisel's code and it's able to use [1.9.4, 1.11] It just works, I have no idea why.

**Comment by Kalman98** [comment]
That was exactly what I was basing my fix on. Chisel. Pushing now.
