### ISSUE TITLE
Daggers Are Not Weapons

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#15]
They do not take damage and do not render in your hand correctly.

**Comment by ParkerMc** [comment]
I can work on this if I get gradle working

**Comment by Kalman98** [comment]
Actually I was about to work on this, I already went through the code to see how it should work. The daggers are registered as normal items with a damage attribute instead of actual swords with modified attributes. It's slightly complicated to figure out how it all works, but if you'd like you can try your hand at it before me.

**Comment by ParkerMc** [comment]
If you know how go right ahead I am still trying to get gradle working I think i have it working now but idk.

**Comment by Kalman98** [comment]
Oh, what is your problem? I recently had a LOT of problems with gradle but I got it working in the end. Maybe I can help.

**Comment by Kalman98** [comment]
Just testing what reopening an issue does. This issue is now fixed.
