### ISSUE TITLE
Bridge Blocks Are OP

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#17]
No idea how to fix this. We could blacklist TNT but that still doesn't help much when other mods are used. Any ideas?

**Comment by CircuitLord** [comment]
Most tnt mods use redstone to light the tnt right? How about we just blacklist redstone blocks?

**Comment by ParkerMc** [comment]
Could you make it so that the tnt(or other block) would not explode?

**Comment by Kalman98** [comment]
I fixed it. Bridge blocks can now only place blocks that endermen can place. Which unfortunately includes TNT, so I added a config option to ban TNT from bridge blocks.
