### ISSUE TITLE
Jewel And Blaze Soups Are More OP Than Bridge Blocks

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#18]
I'm sorry Circuit, but they just are. Regeneration and Resistance should NEVER go together. Maybe we should lower the length of the effects or take some away? Seems reasonable. I'm wondering if we have too many potion effect items anyway though. Nothing takes netherwart to brew.

**Comment by CircuitLord** [comment]
Yeah, I realised that. Its fixed now.
