### ISSUE TITLE
Config does not work at all.

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#19]
When adjusting the config in-game, it does not save or apply the changes. It also duplicates the options in the config for some unknown reason, and overall I think the current code is completely wrong. I really don't know what to do about it though, since @pianoman373 wrote the original code maybe he can help.

**Comment by pianoman373** [comment]
I'll see what I can do.

**Comment by Kalman98** [comment]
Thanks piano, but thanks to the help of the guys on the KreezCraft server I managed to get it working. You can check out the code to see how it works as I'm pushing it now.

**Comment by pianoman373** [comment]
What on earth is the kreezcraft server?

**Comment by Kalman98** [comment]
The modder chat server me and @CircuitLord joined a few days ago.
