### ISSUE TITLE
Computations

### ISSUE THREAD

**Issue by CircuitLord** [TEAMModding/KalStuff#2]
There is a serious problem... I have no idea how to fix it. Here it is... The KalStuff mod is becoming to awesome. My brain cannot handle the awesomeness of it for long...

**Comment by Kalman98** [comment]
Whaaaaaaaa?

**Comment by CircuitLord** [comment]
Ha ha! :)

**Comment by CircuitLord** [comment]
By the way, who is the kodek person?

**Comment by CircuitLord** [comment]
KodekPL

**Comment by Kalman98** [comment]
For some reason, me when I made my first couple of commits. I left the
Author email as the default, which was something like null@mcspigot.com. I
guess it was KodekPL's email.

**Comment by CircuitLord** [comment]
Wow, okay.

**Comment by PieCoder314** [comment]
I believe the only way to fix this bug is to de-awesomeize the mod, which could be extremely dangerous. This glitch is going to have to remain in the mod.
