### ISSUE TITLE
The TEAM is Gone

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#3]
I have not seen, talked to or heard from any other members of the TEAM for five days now. I am the only person still pushing updates to the mod. I fear something has happened to the others. Something bad. TEAM members, if you ever read this, can you please notify me somehow that your are still alive?

**Comment by PieCoder314** [comment]
Haha! I think you are the only one committing because you are the only one left with good ideas.

**Comment by Kalman98** [comment]
You're alive! Thank goodness!

**Comment by Kalman98** [comment]
Well, that may be the case... but I was also worried because no one was even responding to what I had committed. And honestly, what's I've added over the past few days is awesome.

**Comment by pianoman373** [comment]
I havent been pushing anything becuase i'm still trying to get IO to work for .worldgen files. Also i have been extremely busy lately learning python, C++, openGL, working on my mom's website etc.

**Comment by pianoman373** [comment]
I guess i kinda finished python, and C++ isn't working though.

**Comment by pianoman373** [comment]
But yeah, i'm still working on a big update and haven't had much time to finish it.

**Comment by Kalman98** [comment]
Yay, you're also alive! And interesting.

**Comment by Kalman98** [comment]
You know, I think to help with no one else having ideas I'll start an official KalStuff Survival server.

**Comment by Kalman98** [comment]
There we can play and figure out what we don't like or what would be cool to add.

**Comment by pianoman373** [comment]
You should do that when we finish alpha 1.0.

**Comment by pianoman373** [comment]
Otherwise we would have to update every commit.

**Comment by Kalman98** [comment]
Or we could just update every so often.

**Comment by Kalman98** [comment]
I actually think I could set it up pretty easily so that the server would automatically download the latest version of the mod.

**Comment by pianoman373** [comment]
Yeah we would make release versions.

**Comment by pianoman373** [comment]
Once i get my commit in i might look into an alpha 1.0 release.

**Comment by Kalman98** [comment]
I want to get 20 new features before we release anything.

**Comment by Kalman98** [comment]
Not counting items used to craft stuff, like bacon cores and empty mugs.

**Comment by pianoman373** [comment]
Lol i could just make 20 .worldgen files.

**Comment by Kalman98** [comment]
Yeah... no.

**Comment by Kalman98** [comment]
From what it looks like, we have about 10 new features right now. Not counting all the random compaction blocks there are.

**Comment by Kalman98** [comment]
Those being chicken nests, bridges, bacon wands, grapes, squid mats, trash cans, coffee, tea, jewel soup and crushed ender. Oh, and random huts I guess.

**Comment by Kalman98** [comment]
Wow this got way off topic really fast. I guess I'll close it. Apparently most of us are still alive.

**Comment by CircuitLord** [comment]
I am still, working on a bigger update.

**Comment by Kalman98** [comment]
Woohoo, you're alive too!

**Comment by CircuitLord** [comment]
Ha ha!

**Comment by Kalman98** [comment]
You know, I don't think Parker has done anything on here since I first set up the repository. He may have died a while ago.

**Comment by Kalman98** [comment]
The most recent thing he's done is become a member of TEAMModding.

**Comment by pianoman373** [comment]
Because his repository isn't set up

**Comment by Kalman98** [comment]
Maybe that's because he died.

**Comment by Kalman98** [comment]
I know what I'll do.

Hey Parker, are you dead?

**Comment by PieCoder314** [comment]
I saw Parker at mass on Saturday. He may have died since then.

**Comment by Kalman98** [comment]
Don't use people's real names on here without asking them first, please.

**Comment by ParkerMc** [comment]
i am still alive but I've had a lot to do

**Comment by ParkerMc** [comment]
we need to make a milestone
