### ISSUE TITLE
Incorrect text when using spawn eggs on bridge blocks

### ISSUE THREAD

**Issue by CircuitLord** [TEAMModding/KalStuff#32]
Pretty self explainitory, however that's spelled. It does this for any item as well.
![2017-03-25_12 14 06](https://cloud.githubusercontent.com/assets/11892359/24324475/c5689c82-1154-11e7-9ef6-cfdabd55b3d3.png)

**Comment by ParkerMc** [comment]
Could we just change it to item since blocks are items? or do we want it to be "block or item"?

**Comment by Kalman98** [comment]
I think we can just remove "block" so it says "The bridge is unable to send this".
