### ISSUE TITLE
Blocks consumed when used on bridge blocks at build limit

### ISSUE THREAD

**Issue by CircuitLord** [TEAMModding/KalStuff#33]
If you have a bridge block facing into the build limit, and use a  block on it, it will consume the block, but not place it. The chances of this happening are very low, but still possible.

**Comment by Kalman98** [comment]
I feel like I already fixed this once, but with all of the code overhauls there's no telling how it broke again. I'll find a fix for it.

**Comment by Kalman98** [comment]
Interesting, this shouldn't even be possible, given the error checks in the code. Apparently the game thinks the blocks place fine, so I'll have to find a way to detect when it's outside the boundaries of the world.

**Comment by Kalman98** [comment]
Oh, duh, I figured it out. The error checks were in place, but I forgot to put the code that runs on success inside of the `if` statement....
