### ISSUE TITLE
Walking sticks are OP

### ISSUE THREAD

**Issue by pianoman373** [TEAMModding/KalStuff#36]
There is really no reason to not use them in your offhand at all times. I'm thinking maybe they should have a negative effect on the player as a trade-off to traveling easily. A small amount of slowness could work, or it could eat hunger faster. Walking sticks should also probably take damage after so much use, so using them _all_ the time would be unnecessary.

**Comment by Kalman98** [comment]
As of KalStuff for Minecraft 1.12.2, walking sticks have 32 durability which goes down whenever an entity is hit with them. They also do 3 damage per hit. I think this is balance enough for the walking stick, feel free to re-open this issue if you have some changes in mind.
