### ISSUE TITLE
Ideas for KalStuff

### ISSUE THREAD

**Issue by pianoman373** [TEAMModding/KalStuff#4]
Allright, if anyone has any good ideas from now on, comment them in here. If you decide to start working on this idea please notify that you are. Otherwise we'll have two people working on the same thing and that would make a mess.

**Comment by Kalman98** [comment]
This isn't exactly an issue...

**Comment by pianoman373** [comment]
Well there's no way to post 'ideas'.

**Comment by Kalman98** [comment]
Maybe we should just add a "Suggestions" text file on the main page of the repository.

**Comment by Kalman98** [comment]
It would be more organized too.

**Comment by pianoman373** [comment]
Ok how about the readme?

**Comment by pianoman373** [comment]
That way it's on the front page.

**Comment by Kalman98** [comment]
Hm...

**Comment by Kalman98** [comment]
I guess so. Move down a little on it and put SUGGESTIONS in big letters.

**Comment by pianoman373** [comment]
Done.
