### ISSUE TITLE
Trash Can Magic Trick

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#5]
Trash cans don't drop when you break them. They break instantly and then vanish.

**Comment by pianoman373** [comment]
Wow, I'll fix that in my next commit.

**Comment by Kalman98** [comment]
I could fix it myself but it's your code, so I'll let you fix it.

**Comment by Kalman98** [comment]
By the way, I'm on Mumble right now. Off topic!

**Comment by ParkerMc** [comment]
did you fix it?

**Comment by pianoman373** [comment]
No not yet

**Comment by pianoman373** [comment]
Oh yeah forgot to close this with my last push.
