### ISSUE TITLE
Spoiler

### ISSUE THREAD

**Issue by pianoman373** [TEAMModding/KalStuff#7]
Well since kal says we need to add alot more features I guess the pre-release will come later. So i decided to start working on something big...... very big. Here's a spoiler of what i'm working on.
![test](https://cloud.githubusercontent.com/assets/11893049/7634634/dbea391c-fa21-11e4-85e2-c8a96085d7b9.png)

**Comment by PieCoder314** [comment]
I have no idea what that could possibly be.

**Comment by pianoman373** [comment]
Lol you'll see...

**Comment by PieCoder314** [comment]
Whatever it is, it looks very blue and very green.

**Comment by Kalman98** [comment]
@PieCrafter314 , from the image it looks like he's adding perfect beaches. But it could also be coral reefs, smoothed out islands under the ocean, or weird tropical moon altars.

**Comment by Kalman98** [comment]
I don't see how this counts as an issue, however.

**Comment by PieCoder314** [comment]
My guess is the islands.

```
____       __
```

   / __ ___  / /____  _____
  / /_/ / _ \/ __/ _ \/ **_/
 / _**_/  **/ /_/  __/ /
/_/    \_**/__/___/_/

Not sent from my iPhone because I don't have one

**Comment by pianoman373** [comment]
I labeled it as enhancement though. I can't really find anywhere else to post comments like this. I wish we had our own forum or something

And as a hint, it'll have something to do with custom world types....

**Comment by PieCoder314** [comment]
Better water world generation?

```
____       __
```

   / __ ___  / /____  _____
  / /_/ / _ \/ __/ _ \/ **_/
 / _**_/  **/ /_/  __/ /
/_/    \_**/__/___/_/

Not sent from my iPhone because I don't have one

**Comment by pianoman373** [comment]
That's all the hints I'm gonna give out for now.

**Comment by Kalman98** [comment]
A forum would be cool. But we would need a private VIP forum for developers only as a subforum.

**Comment by pianoman373** [comment]
Yeah

**Comment by PieCoder314** [comment]
We could set something up on freeforums.net or something like that.

```
____       __
```

   / __ ___  / /____  _____
  / /_/ / _ \/ __/ _ \/ **_/
 / _**_/  **/ /_/  __/ /
/_/    \_**/__/___/_/

Not sent from my iPhone because I don't have one

**Comment by PieCoder314** [comment]
I can get to work on that if you guys want.

**Comment by pianoman373** [comment]
I don't really know how freeforums.net works. I would think we would need a website to have our own forums.

**Comment by PieCoder314** [comment]
Freeforums.net is pretty much just a website that helps you to make your own forum website.

**Comment by pianoman373** [comment]
Yeah so we should do that once we start looking into a website for the TEAM.

**Comment by PieCoder314** [comment]
We could do that on weebly. Parker, LOTRfan02 and I worked on a [website](orchardco-op.weebly.com) for a homeschool co-op we go to with weebly.

**Comment by pianoman373** [comment]
I'm not sure what weebly is either. If we made a website for the TEAM we could probably just do plain HTML.

**Comment by PieCoder314** [comment]
I just made a test forum. Check it out at http://teammodders.freeforums.net/.

**Comment by pianoman373** [comment]
Wow, that looks really cool.

**Comment by Kalman98** [comment]
He could also be stealing the LOTR Mod's idea of generating terrain based on image files.

**Comment by pianoman373** [comment]
If anyone didn't get circuit's email a minute ago, me and him are on mumble discussing website idea's.
We need everyone on to settle the TEAM name.

**Comment by ghost** [comment]
my account got hacked this is my new one

**Comment by PieCoder314** [comment]
Your account got hacked! Seriously?!? Who did that?

.--. . - . .-.    --.. . .-. .- -. --. ..- .

**Comment by Kalman98** [comment]
Wow. Who, and why would they want to? And also, how do you know?

**Comment by ghost** [comment]
i do not know who did it
i can not get on my old one someone changed the email

**Comment by PieCoder314** [comment]
Was it Daniel? Lol

.--. . - . .-.    --.. . .-. .- -. --. ..- .

**Comment by Kalman98** [comment]
That's weird. Well next time you're on the server, tell me and I'll add you to the group with your new account.

**Comment by pianoman373** [comment]
Wow, so how do we know this is really you?

**Comment by ghost** [comment]
no i ment my github acount
here i will send you an email

**Comment by Kalman98** [comment]
I removed your old GitHub account from the group for now.

**Comment by ghost** [comment]
ok thx

**Comment by pianoman373** [comment]
I was starting to think everyone in the TEAM died now... we havent had any code changes in weeks.

**Comment by pianoman373** [comment]
appareantly it didn't take much to get everyone commenting again.

**Comment by Kalman98** [comment]
As it happens I was working on the mod right when he said his account got hacked. Still am.

**Comment by Kalman98** [comment]
I've added lots of floatiness.

**Comment by pianoman373** [comment]
I actually need to close this enhancement because i gave up on this project a long time ago...

**Comment by ghost** [comment]
it got hacked a day or tow ago

**Comment by Kalman98** [comment]
Wow. Okay.
Maybe we should all get on Mumble.

**Comment by pianoman373** [comment]
You guys were right, i was copying LOTR a bit and trying to make custom islands.

**Comment by pianoman373** [comment]
ok

**Comment by Kalman98** [comment]
Ha ha!

**Comment by Kalman98** [comment]
Well then, goodbye Issue #7.

Oooooh auto link added.

**Comment by ghost** [comment]
can you email me the server ip for mumble kal?

**Comment by Kalman98** [comment]
I thought you had the IP?

On Thu, May 28, 2015 at 2:04 PM, parkerkid notifications@github.com wrote:

> can you email me the server ip for mumble kal?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEAMModding/KalStuff/issues/7#issuecomment-106567719.

## 

Kalvin

".ot stnaw eh nehw yltcaxe sevirra tub ,ylrae ron etal rehtein si draziw A"
- Gandalf arriving at the international speed-gun meet.

It could use some more mustard.

**Comment by ghost** [comment]
no i do not have it is it still in dropbox?
