### ISSUE TITLE
Mod Name

### ISSUE THREAD

**Issue by Kalman98** [TEAMModding/KalStuff#8]
Before I release the mod, we need to figure out the official name. Is it gonna be KalStuff? I assume you guys won't want it named after me. And remember: Random Stuff is already a mod. So any ideas as to what we should call this? Once we decide I'll update all the code.

**Comment by CircuitLord** [comment]
Yeah KalStuff is good.

**Comment by pianoman373** [comment]
Yeah kalstuff is fine since it is your mod.

**Comment by PieCoder314** [comment]
Kalstuff is fine with me.

**Comment by Kalman98** [comment]
Alright guys, thanks. KalStuff it is!
