### ISSUE TITLE
picking a new mod

### ISSUE THREAD

**Issue by pianoman373** [TEAMModding/KalStuff#9]
Alright guys it's that time! time to vote for the next official mod we'll work on.
We currently have three suggested mod ideas. You can wither vote for one by commenting on this or proposing a mod idea yourself. Whatever mod the majority of the team can agree on we'll start working on. the three currently proposed mod ideas are:
1. kalman98's Catholicism mod idea: 
   A mod about Catholicism. 
   Masses and Sacraments and Sacrementals.
   Scripture, Magisterium, Tradition.
   Faith, Hope and Love.
   Father, Son and Holy Spirit.
   Saints and saints.
   Heaven and Hell.
2. pianoman373's futurecraft idea:
   Physics based space travel, orbits, planets, buildable spacecraft,
   Electricity-based machinery, high-tech battle gear, alien civilizations,
   lots and lots of space physics.
   Essentially a cross between minecraft and spaceEngine.
3. blackout4488's foodies idea:
   Extra food, baking and cooking based mechanics.

**Comment by pianoman373** [comment]
Sorry that should have been 'either vote' instead of 'wither vote', withers CANNOT vote

**Comment by CircuitLord** [comment]
I think a underwater mod would be cool. Basically flans mod for underwater.
CircuitLord's Underwater mod idea:
Submarines, water suits, oxygen tanks.
Sea life, buried treasure, sunken ships.
Underwater battle gear.

**Comment by pianoman373** [comment]
I guess i'll vote for the Catholicism mod.

**Comment by PieCoder314** [comment]
Those all sound like great ideas. I'm voting "All of the above".

**Comment by pianoman373** [comment]
We cant work on all of them at the same time... you have to pick one.

**Comment by PieCoder314** [comment]
I'm not saying we should do all at once, I'm just saying I can't pick just one, so I'll do whatever gets voted.

**Comment by pianoman373** [comment]
Oh, ok.

**Comment by Kalman98** [comment]
I pick FutureCraft.

**Comment by pianoman373** [comment]
Did everyone vote if we're gonna vote yet?

**Comment by Kalman98** [comment]
We still need Parker, Angelgal and the Creeps to vote.

**Comment by CircuitLord** [comment]
I don't really care which mod we do. Although, if we vote for the method where we work on random things, this doesn't really matter.

**Comment by pianoman373** [comment]
Yeah if we pick to do random mods this vote doesn't matter.

**Comment by ghost** [comment]
i vote for futurecraft

**Comment by CircuitLord** [comment]
I vote for FutureCraft as well. Parker told me that FutureCraft would include some of the things I liked in the Underwater mod. Ect. Submarines.

**Comment by ghost** [comment]
that is what @ploquel told me

**Comment by pianoman373** [comment]
Yeah we will need some sort of underwater craft for water planets and Europa but I'm not promising it'll make it in.

**Comment by CircuitLord** [comment]
Okay, thats fine.

**Comment by ghost** [comment]
who did not vote yet?

**Comment by pianoman373** [comment]
We're still waiting on kal to release who won the votes for the method we'll use.
if the free way won than this vote doesnt even matter.

**Comment by ghost** [comment]
let me vote real quick i forgot

**Comment by CircuitLord** [comment]
You voted for Future craft already.

**Comment by ghost** [comment]
no for the method we'll use

**Comment by ghost** [comment]
lol @CircuitLord you have 32 bit java

**Comment by CircuitLord** [comment]
No I don't.

**Comment by Kalman98** [comment]
We are using the Focused Way!

Also, I would like to remove The Catholicism Mod from this vote. I want to work on it on my own for a while, maybe the TEAM can work on it later. So if you voted for The Catholicism Mod, vote again.

**Comment by pianoman373** [comment]
Hmmmmm...

I guess I vote for the underwater idea.

**Comment by CircuitLord** [comment]
Wow. I guess I'm going to vote for underwater too then.

**Comment by pianoman373** [comment]
Although we have 4 votes for futurecraft and only 2 voters left.

**Comment by pianoman373** [comment]
No, you cant vote for your own mod. or i would have voted for futurecraft.

**Comment by CircuitLord** [comment]
Hey, I pulled up my eclipse just now. (It has been like a month since I opened it) and it is having problems pulling.

**Comment by CircuitLord** [comment]
How do I reset my workspace again?

**Comment by CircuitLord** [comment]
Oh okay. I vote for futurecraft then.

**Comment by pianoman373** [comment]
I believe you right click the root repository and click replace with HEAD revision or something like that.

**Comment by CircuitLord** [comment]
This is the error it had if your wondering. Cannot pull into a repository with state: MERGING

**Comment by ghost** [comment]
what did i tell you @CircuitLord is was 32bit

**Comment by CircuitLord** [comment]
Lol it was. Not anymore though.

**Comment by CircuitLord** [comment]
Replace with HEAD revision is grayed out. I'm doing replace with previous revision.

**Comment by Kalman98** [comment]
If this is your workspace for KalStuff, it sounds like you just need to delete everything and make a fresh pull.

**Comment by CircuitLord** [comment]
Oh, good idea. I just tried the replce with previous revision and it still has errors.

**Comment by CircuitLord** [comment]
How can I pull if the file is not there?

**Comment by Kalman98** [comment]
It looks like we have 1 vote for the underwater mod and 3 for FutureCraft so far.

**Comment by Kalman98** [comment]
Circuit, copy this link and then right click in your repositories tab.

https://github.com/TEAMModding/KalStuff.git

**Comment by Kalman98** [comment]
By the way, you guys do realize that anyone could see this conversation, right?

**Comment by CircuitLord** [comment]
Yeah, why?

**Comment by Kalman98** [comment]
Just sayin'. I'd rather us not have conversations in the Issues section.

**Comment by Kalman98** [comment]
And I am on Mumble.

**Comment by pianoman373** [comment]
moneybiz emailed me earlier today saying he voted futurecraft, not sure if it was black or nunya and why they only emailed me...

**Comment by Kalman98** [comment]
Wow. I'm the one who forwarded this conversation to them, so weird.

**Comment by PieCoder314** [comment]
I guess since we decided on futurecraft, this issue is resolved. I'm closing it now. If I shouldn't be doing this, someone fix it.

**Comment by Kalman98** [comment]
Yeah, I think it's over. It wasn't an issue though. Please guys, use email instead of the issues section to talk from now on.
